name: Gajim

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: check working directory
        run: ls
      - name: Build Gajim
        run: cd ${GITHUB_WORKSPACE} && bash ${GITHUB_WORKSPACE}/gajim-macos-helper.sh build
      - name: Create Gajim dmg
        run: cd ${GITHUB_WORKSPACE} && bash ${GITHUB_WORKSPACE}/gajim-macos-helper.sh create-dmg
