name: Gajim

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build Gajim
        run: bash ${GITHUB_WORKSPACE}/gajim-macos-helper.sh build
      - name: Create Gajim dmg
        run: bash ${GITHUB_WORKSPACE}/gajim-macos-helper.sh create-dmg
      - uses: actions/upload-artifact@v4
        with:
          name: gajim.dmg
          path: ${GITHUB_WORKSPACE}/gajim-source/gajim-*.dmg
